# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bitc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nbitc.proto"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t"\x19\n\x08GetReply\x12\r\n\x05value\x18\x01 \x01(\t"\n\n\x08PutReply"\x1d\n\x0b\x44\x65leteReply\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x83\x01\n\x15\x42itCdbKeyValueService\x12\x1f\n\x03get\x12\x0b.GetRequest\x1a\t.GetReply"\x00\x12\x1f\n\x03put\x12\x0b.PutRequest\x1a\t.PutReply"\x00\x12(\n\x06\x64\x65lete\x12\x0e.DeleteRequest\x1a\x0c.DeleteReply"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "bitc_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _GETREQUEST._serialized_start = 14
    _GETREQUEST._serialized_end = 39
    _PUTREQUEST._serialized_start = 41
    _PUTREQUEST._serialized_end = 81
    _DELETEREQUEST._serialized_start = 83
    _DELETEREQUEST._serialized_end = 111
    _GETREPLY._serialized_start = 113
    _GETREPLY._serialized_end = 138
    _PUTREPLY._serialized_start = 140
    _PUTREPLY._serialized_end = 150
    _DELETEREPLY._serialized_start = 152
    _DELETEREPLY._serialized_end = 181
    _BITCDBKEYVALUESERVICE._serialized_start = 184
    _BITCDBKEYVALUESERVICE._serialized_end = 315
# @@protoc_insertion_point(module_scope)
